name: Timezones
version: '${version}'
main: io.github.metriximor.timezones.TimezonesPlugin
api-version: '1.18'
author: Metriximor
softdepend: [ ChunkyBorder ]
permissions:
  timezone.toggle:
    description: "Timezone allows the behaviour of the plugin to be toggled on or off"
    default: op
commands:
  timezone:
    description: "Timezone command for quick admin control"
    usage: "/timezone <enable/disable/version>"
    aliases:
      - tz
    permission: timezone.toggle
    permission-message: "You do not have permission to toggle timezones"
